name: Zarin
description: Zarin Shop

publish_to: 'none'

version: 1.0.8+8

environment:
  sdk: ">=2.7.0 <3.0.0"

dependencies:
  flutter:
    sdk: flutter
  
  flutter_localizations:
    sdk: flutter

  connectivity: ^0.4.9+3
  rxdart: ^0.24.1
  http: ^0.12.2
  circular_check_box: ^1.0.4
  shared_preferences: ^0.5.12+2
  flutter_secure_storage: ^3.3.5
  google_nav_bar: ^3.1.0
  credit_card_input_form: ^2.1.3
  persistent_bottom_nav_bar: ^2.1.0
  shimmer: ^1.1.2
  custom_refresh_indicator: ^0.9.0
  superellipse_shape: ^0.1.5
  photo_view: ^0.10.3
  webview_flutter: ^1.0.7
  crypto: ^2.1.5
  
flutter:
  fonts:
  - family: AppIcons
    fonts:
      - asset: assets/fonts/AppIcons.ttf
  - family: SegoeUI
    fonts:
      - asset: assets/fonts/SegoeUI.ttf
  - family: SegoeUIBold
    fonts:
      - asset: assets/fonts/SegoeUIBold.ttf
  - family: SegoeUISemiBold
    fonts:
      - asset: assets/fonts/SegoeUI-SemiBold.ttf

  uses-material-design: true