# Uncomment the next line to define a global platform for your project
# platform :ios, '11.0'

target 'ZarinShop' do
  # Comment the next line if you don't want to use dynamic frameworks
  use_frameworks!

  inhibit_all_warnings!

  # Pods for ZarinShop
  pod 'SnapKit', '4.2.0'
  pod 'SideMenuSwift'
  pod 'BetterSegmentedControl', '~> 1.3'
  pod 'ColorMatchTabs'
  pod 'Reveal-SDK', :configurations => ['Debug']

end
