version: '3.1'

services:
  mongo:
   image: mongo
   container_name: zarinshop-mongo
   restart: always
   environment:
     MONGO_INITDB_ROOT_USERNAME: root
     MONGO_INITDB_ROOT_PASSWORD: example
   ports:
     - 27017:27017
   volumes:
     - "./.docker/db:/data/db"

  mongo-express:
    image: mongo-express
    container_name: zarinshop-mongo_express
    restart: always
    ports:
      - 8082:8081
    environment:
      ME_CONFIG_MONGODB_ADMINUSERNAME: root
      ME_CONFIG_MONGODB_ADMINPASSWORD: example
    